django/auth/crud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from posts import views
urlpatterns = [
    path('accounts/', include('acoounts.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/auth/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.index, name='list'),  # GET
    # path('create/',views.create, name='create'), 
    
    path('new/',views.new, name='new'), # GET(new), POST(create)
    path('<int:post_id>/',views.detail, name='detail'), # GET
    path('<int:post_id>/delete/',views.delete, name='delete'),  # GET(confirm), POST(delete)
    path('<int:post_id>/edit/', views.edit, name='edit'),   # GET(edit), POST(update)
    # path('<int:post_id>/update/',views.update, name='update'),
    path('<int:post_id>/comments/create/', views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete', views.comments_delete, name='comments_delete'),
]

django/cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('person/',include('person.urls')),
]

django/crud/crud/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

django/instad/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('<str:username>/',views.list,name='list'),
    path('<str:username>/create/',views.create,name='create'),
    path('<str:username>/<int:post_id>/update/',views.update, name='update'),
    path('<str:username>/<int:post_id>/delete/',views.delete,name='delete'),
    path('<str:username>/<int:post_id>/comments/create/',views.comment_create,name='comment_create'),
    path('<str:username>/<int:post_id>/comments/<int:comment_id>/delete/',views.comment_delete,name="comment_delete"),
    path('<str:username>/<int:post_id>/like/',views.like,name="like"),
    # path('<int:post_id>/like/togo',views.liketogo,name='liketogo'),
]

django/orm/orm/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django/crud-plus/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
        
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    
    # on_delete 옵션
    # 1. CASCADE : 부모가 삭제되면, 자기 자신도 삭제.
    # 2. PROTECT : 자식이 존재하면, 부모 삭제 불가능.
    # 3. SET_NULL : 부모가 삭제되면, 자식의 부모 정보에 NULL 설정.
    

# 1. Create
# post = Post(title='helo', content='world!') =>처음 post는 변수이름 뒤 Post 는 클래스이름
# post.save()

# 2. Read

# 2.1. All
# posts = Post.objects.all()

# 2.2 Get one
# post = Post.objects.get(pk=1)

# 2.3 filter
# posts = Post.objects.filter(title='hello')
# post = Post.objects.filter(title='hello').first()

# Like
# posts = Post.objects.filter(titl__contains='He').all()

# 2.5 order_by (정렬)
# posts = Post.objects.order_by('title').all() #=> 오름차순
# posts = Post.objects.order_by('-title').all() #=> 내림차순

# 2.6 limit & offset
# [offset:offset+limit]
# posts = Post.objects.all()[1:2]

# 3. Delete
# post = Post.objects.get(pk=2)
# post.delete()

# 4. Update
# post = Post.objects.get(pk=1)
# post.title = 'hi'
# post.save()

django/exercise/exer_190211/post/models.py
from django.db import models

# Create your models here.
class Food(models.Model):
    name = models.CharField(max_length=100)
    calorie = models.IntegerField()
    ingredients = models.TextField()
    category = models.CharField(max_length=100)

django/exercise/post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.TextField()
    content = models.TextField()

django/insta-1.1/posts/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)

django/insta-1/posts/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_posts',blank=True)
    

django/insta2/post/models.py
from django.db import models

# Create your models here.

django/ws19/post/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    birthday = models.DateField(max_length=100)
    age = models.IntegerField()
    
class Post(models.Model):
    name = models.CharField(max_length=100)
    message=models.TextField()

django/exercise/exer_190211/post/forms.py
from django import forms
from .models import Food

class mainq(forms.Form):
    category = forms.CharField()
    
class PostModelForm(forms.ModelForm):
    category = forms.CharField()
    class Meta:
        model = Food
        fields = ['name','calorie','ingredients','category']

django/insta/insta/posts/forms.py
from django import forms
from .models import Post,Comment,Image

class PostForm(forms.ModelForm) :
    class Meta :
        model = Post
        fields = ['content',]

class ImageForm(forms.ModelForm) :
    class Meta :
        model = Image
        fields = ['file',]
        

ImageFormSet = forms.inlineformset_factory(Post,Image,form =ImageForm, extra=3)

class CommentForm(forms.ModelForm) :
    content = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'댓글을 작성하세요.'}))
    
    class Meta :
        model = Comment
        fields = ['content',]
    

django/insta/posts/forms.py
from django import forms
from .models import post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = post
        fields = ['content','image',]

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder':'댓글을 작성하세요'}))
    class Meta:
        model = Comment
        fields = ['content',]

django/instad/posts/forms.py
from django import forms
from .models import post,Comment,Image

class PostForm(forms.ModelForm):
    class Meta:
        model = post
        fields = ['content',]
        
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]
ImageFormset = forms.inlineformset_factory(post,Image,form=ImageForm,extra=3)

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder':'댓글을 작성하세요'}))
    class Meta:
        model = Comment
        fields = ['content',]

django/crud-files/posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
# Create your views here.

#def throw
#def catch
def new(request):
    return render(request,'new.html')
    
def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    image = request.FILES.get('image')
    
    post = Post(title=title,content=content,image=image)
    post.save()
    
    return redirect('posts:detail',post.pk)
    # return render(request,'create.html')

def index(request):
    # All post
    posts = Post.objects.all()
    
    return render(request,'index.html',{'posts':posts})
    
def detail(request,post_id):
    post = Post.objects.get(pk=post_id)
    # comments = post.comment_set.all()
    return render(request,'detail.html',{'post':post})
    
def naver(request,q):
    
    return redirect(f'https://search.naver.com/search.naver?query={q}')
    
def github(request,username):
    return redirect(f'https://github.com/{username}')
    
def delete(request,post_id):
    post = Post.objects.get(pk=post_id)
    # 삭제하는 코드
    post.delete()
    return redirect('posts:list')

def edit(request,post_id):
    post = Post.objects.get(pk=post_id)
    return render(request,'edit.html',{'post':post})

def update(request,post_id):
    post = Post.objects.get(pk=post_id)
    post.title = request.POST.get('title')
    post.content = request.POST.get('content')
    post.save()
    return redirect('posts:detail',post.pk)
    
def comments_create(request,post_id):
    content=request.POST.get('content')
    post = Post.objects.get(pk=post_id)
    comment = Comment(post=post,content=content)
    comment.save()
    return redirect('posts:detail',post_id)

def comments_delete(request,post_id,comment_id):
    comment=Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('posts:detail',post_id)
    

django/crud-plus/posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
# Create your views here.

#def throw
#def catch
def new(request):
    return render(request,'new.html')
    
def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    
    
    post = Post(title=title,content=content)
    post.save()
    
    return redirect('posts:detail',post.pk)
    # return render(request,'create.html')

def index(request):
    # All post
    posts = Post.objects.all()
    
    return render(request,'index.html',{'posts':posts})
    
def detail(request,post_id):
    post = Post.objects.get(pk=post_id)
    # comments = post.comment_set.all()
    return render(request,'detail.html',{'post':post})
    
def naver(request,q):
    
    return redirect(f'https://search.naver.com/search.naver?query={q}')
    
def github(request,username):
    return redirect(f'https://github.com/{username}')
    
def delete(request,post_id):
    post = Post.objects.get(pk=post_id)
    # 삭제하는 코드
    post.delete()
    return redirect('posts:list')

def edit(request,post_id):
    post = Post.objects.get(pk=post_id)
    return render(request,'edit.html',{'post':post})

def update(request,post_id):
    post = Post.objects.get(pk=post_id)
    post.title = request.POST.get('title')
    post.content = request.POST.get('content')
    post.save()
    return redirect('posts:detail',post.pk)
    
def comments_create(request,post_id):
    content=request.POST.get('content')
    post = Post.objects.get(pk=post_id)
    comment = Comment(post=post,content=content)
    comment.save()
    return redirect('posts:detail',post_id)

def comments_delete(request,post_id,comment_id):
    comment=Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('posts:detail',post_id)
    

django/crud-rest/posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
# Create your views here.

#def throw
#def catch
def new(request):
    if request.method == 'GET':
        return render(request,'new.html')
    else :
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        
        post = Post(title=title,content=content,image=image)
        post.save()
    
        return redirect('posts:detail',post.pk)
    
# def create(request):
#     title = request.POST.get('title')
#     content = request.POST.get('content')
#     image = request.FILES.get('image')
    
#     post = Post(title=title,content=content,image=image)
#     post.save()
    
#     return redirect('posts:detail',post.pk)
#     # return render(request,'create.html')

def index(request):
    # All post
    posts = Post.objects.all()
    
    return render(request,'index.html',{'posts':posts})
    
def detail(request,post_id):
    post = Post.objects.get(pk=post_id)
    # comments = post.comment_set.all()
    return render(request,'detail.html',{'post':post})
    
def naver(request,q):
    
    return redirect(f'https://search.naver.com/search.naver?query={q}')
    
def github(request,username):
    return redirect(f'https://github.com/{username}')
    
def delete(request,post_id):
    if request.method == 'POST':
        post = Post.objects.get(pk=post_id)
        # 삭제하는 코드
        post.delete()
        return redirect('posts:list')
    else:
        return render(request,'delete.html')

def edit(request,post_id):
    post = Post.objects.get(pk=post_id)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('posts:detail',post.pk)
    else :
        return render(request,'edit.html',{'post':post})

# def update(request,post_id):
#     post = Post.objects.get(pk=post_id)
#     post.title = request.POST.get('title')
#     post.content = request.POST.get('content')
#     post.save()
#     return redirect('posts:detail',post.pk)
    
def comments_create(request,post_id):
    content=request.POST.get('content')
    post = Post.objects.get(pk=post_id)
    comment = Comment(post=post,content=content)
    comment.save()
    return redirect('posts:detail',post_id)

def comments_delete(request,post_id,comment_id):
    comment=Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('posts:detail',post_id)
    

django/crud/posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

#def throw
#def catch
def new(request):
    return render(request,'new.html')
    
def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    post = Post(title=title,content=content)
    post.save()
    return render(request,'create.html')

def index(request):
    # All post
    posts = Post.objects.all()
    
    
    return render(request,'index.html',{'posts':posts})

django/exercise/exer_190211/post/views.py
from django.shortcuts import render,redirect
from .forms import mainq,PostModelForm
from .models import Food
# Create your views here.
def index(request):
    if request.method=="POST":
        form = mainq(request.POST)
        if form.is_valid():
            category = form.cleaned_data.get('category')
            foods = Food.objects.filter(category=category)
            return render(request,'list.html',{'foods':foods,'category':category})
    else:
        mainqs = mainq()
    
    return render(request,'index.html',{'mianq':mainqs})
    
def create(request,category):
    if request.method=="POST":
        print(request.POST)
        form = PostModelForm(request.POST)
        
        if form.is_valid():
            food = form.save()
            foods = Food.objects.filter(category=food.category)
            return render(request,'list.html',{'foods':foods,'category':food.category})
    else:
        form = PostModelForm(initial={'category':category})
    return render(request,'create.html',{'form':form,'category':category})
    
def detail(request,food_id):
    if request.method=='POST':
        category = request.POST.get('category')
        foods = Food.objects.filter(category=category)
        return render(request,'list.html',{'foods':foods,'category':category})
    else:
        food = Food.objects.get(pk=food_id)
        return render(request,'detail.html',{'food':food})
    
def update(request,food_id):
    food = Food.objects.get(pk=food_id)
    if request.method=="POST":
        form = PostModelForm(request.POST,instance=food)
        if form.is_valid():
            food = form.save()
            foods = Food.objects.filter(category=food.category)
            return redirect('post:detail', food.pk)
    else:
        form = PostModelForm(initial={'category':food.category})
    return render(request,'create.html',{'form':form,'category':food.category})
    
def delete(request,food_id):
    food = Food.objects.get(pk=food_id)
    category = food.category
    foods = Food.objects.filter(category=category)
    food.delete()
    return render(request,'list.html',{'foods':foods,'category':category})

django/exercise/post/views.py
from django.shortcuts import render,redirect
from .models import Post
# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request,'index.html',{'posts':posts})

def new(request):
    return render(request,'new.html')
    
def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    post = Post(title=title,content=content)
    post.save()
    return redirect('/post')

def detail(request,post_id):
    post = Post.objects.get(pk=post_id)
    return render(request,'detail.html',{'post':post})
    
def delete(request,post_id):
    post = Post.objects.get(pk=post_id)
    post.delete()
    return redirect('/post')
    
def edit(request,post_id):
    return render(request,'edit.html',{'post_id':post_id})
    
def confirm(request,post_id):
    post = Post.objects.get(pk=post_id)
    post.title = request.POST.get('title')
    post.content = request.POST.get('content')
    post.save()
    return redirect(f'/post/{post_id}/')
    

django/insta/posts/templates/posts/_post.html
<div class="col-4">
  <img src="{{ post.image.url }}" class="card-img-top mb-4" alt="{{ post.image }}" data-toggle="modal" data-target="#abc{{post.id}}">
</div>
<div class="modal fade bd-example-modal-lg" id="abc{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="card" style="width: 100%;">
        <div class="row no-gutters">
          <div class="col-md-8">
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.image }}">
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <a href="{% url 'posts:list' post.user.username %}">
                <h5 class="card-title">{{post.user.username}}</h5>
              </a>
              
              {% if post.user == user %}
              <a href="{% url 'posts:update' username post.id %}" class="btn btn-warning btn-sm">edit</a>
              <a href="{% url 'posts:delete' username post.id %}" class="btn btn-danger btn-sm">delete</a>
              {% endif %}
              <p class="card-text">{{ post.content }}</p>
              <hr>
              <div data-spy="scroll" data-offset="0" height="50%">
                  {% for comment in post.comment_set.all %}
                  <div class="card-text">
                    <a href="{% url 'accounts:people' comment.user.username %}">
                      <strong>@{{comment.user.username}}</strong>
                    </a>
                     | {{comment.content}}
                    {% if comment.user == user %}
                    <a href="{% url 'posts:comment_delete' username post.id comment.id %}">삭제</a>
                    {% endif %}
                  </div>
                  {% empty %}
                  <div class="card-text">댓글이 없습니다.</div>
                  {% endfor %}
                  <hr>
                  <a href='{% url 'posts:like' username post.id %}'>
                  {% if user in post.like_users.all %}
                    <i class="fas fa-heart"></i>
                  {% else %}
                    <i class="far fa-heart"></i>
                  {% endif %}
                  </a>
                  <p class="card-text">
                    {{ post.like_users.count}}명이 좋아합니다.
                  </p>
              </div>
             {% if user.is_authenticated %}
              <div style="position:absolute;bottom:0">
               
                <form action='{% url 'posts:comment_create' username post.id %}' method = 'post'>
                {% csrf_token %}
                <div class="input-group" style="width:100%">
                  {{comment_form}}
                  <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">작성</button>
                  </div>
                </div>
              </form>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">Large modal</button>-->

<!--<div class="col-4">-->
  <!--<img src="{{ post.image.url }}" class="card-img-top mb-4" alt="{{ post.image }}" data-toggle="modal" data-target="#abc{{post.id}}">-->
<!--</div>-->

<!--<div class="modal fade" id="abc{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="width: 1000px;">-->
<!--  <div class="modal-dialog modal-dialog-centered" role="document">-->
<!--    <div class="modal-content">-->
      <!--<div class="modal-header">-->
      <!--  <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>-->
      <!--  <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
      <!--    <span aria-hidden="true">&times;</span>-->
      <!--  </button>-->
      <!--</div>-->
<!--      <div class="modal-body">-->
<!--       <div class="card mb-3" style="width: 800px;">-->
<!--  <div class="row no-gutters">-->
<!--    <div class="col-md-8">-->
<!--      <img src="{{ post.image.url }}" class="card-img-top mb-4" alt="{{ post.image }}" >-->
<!--    </div>-->
<!--    <div class="col-md-4">-->
<!--      <div class="card-body">-->
<!--        <h5 class="card-title">{{post.user.username}}</h5>-->
<!--        <p class="card-text"></p>-->
<!--        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<!--      </div>-->
      <!--<div class="modal-footer">-->
      <!--  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
      <!--  <button type="button" class="btn btn-primary">Save changes</button>-->
      <!--</div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="col-4">-->
<!--  <div class="card mb-2" style="width: 18rem;">-->
<!--  <div class="card-header">-->
<!--    <span>{{post.user.username}}</span>-->
<!--  </div>-->
<!--  <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.image }}">-->
<!--  <div class="card-body">-->
    <!--<p class="card-text">{{ post.content }}</p>-->
    <!--{% if post.user == user %}-->
    <!--<a href="{% url 'posts:update' username post.id %}" class="btn btn-warning">edit</a>-->
    <!--<a href="{% url 'posts:delete' username post.id %}" class="btn btn-danger">delete</a>-->
    <!--{% endif %}-->
<!--    <a class="btn btn-secondary" data-toggle="collapse" href="#abc{{post.id}}" role="button" aria-expanded="false" aria-controls="{{post.id}}">-->
<!--      댓글열기-->
<!--    </a>  -->
<!--  </div>-->
<!--<div class="card-dody">-->
<!--  <div class="collapse" id="abc{{post.id}}">-->
  <!--{% for comment in post.comment_set.all %}-->
  <!--  <div class="card-text">-->
  <!--    <strong>@{{comment.user.username}}</strong> | {{comment.content}}-->
  <!--  </div>-->
  <!--{% empty %}-->
  <!--<div class="card-text">댓글이 없습니다.</div>-->
  <!--{% endfor %}-->
<!--  </div>-->
<!--</div>-->
<!--{% if user.is_authenticated %}-->
<!--<form action='{% url 'posts:comment_create' username post.id %}' method = 'post'>-->
<!--  {% csrf_token %}-->
  
<!--  <div class="input-group mb-3">-->
<!--    {{comment_form}}-->
<!--    <div class="input-group-append">-->
<!--      <button class="btn btn-outline-secondary" type="submit" id="button-addon2">작성</button>-->
<!--    </div>-->
<!--  </div>-->
<!--</form>-->
<!--{% endif %}-->
<!--</div>  -->
<!--</div>-->

django/insta/posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}

<h1>New post</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% buttons %}
        <button type="submit" class="btn btn-warning">Submit</buttons>
    {% endbuttons %}
</form>
{% endblock %}

django/insta/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}


<div class="container">
    <h1>Post form</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% buttons %}
        <button type="submit" class="btn btn-warning">Submit</buttons>
    {% endbuttons %}
</form>
</div>

{% endblock %}